### ISSUE TITLE
Why hallo thare!

### ISSUE THREAD

**Issue by RobLoach** [docpad/docpad-skeleton-benchmark#1]
:baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: :baby: 

Let's add more than 1000 docs. Also eco is rather old, use Jade.

**Comment by pflannery** [comment]
then jade it is! 

though still the same speed with 1000 documents :(, Coffeekup is faster by around 30secs.

I would bump it further than 1000 but its grief checking them in! :)

Changing [the generator file here](https://github.com/pflannery/docpad-large-site-test/blob/master/generate-files.js#L5)
and running `node generate-files.js` will generate them from [this generator template](https://github.com/pflannery/docpad-large-site-test/blob/master/template.html.jade)
